FROM debian:stretch-slim

# TLM base cockroachDB custom build
# created by oyoshi

RUN mkdir /opt/ssl /opt/ssl/certs /opt/ssl/ca

RUN apt-get update && \
    apt-get install -y zssh iputils-ping && \
    apt-get clean && \
   	rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*

EXPOSE 3022 22